version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:14.5
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_DB: ${BAKPGS3_DATABASE}
      POSTGRES_PASSWORD: ${BAKPGS3_PASSWORD}
      POSTGRES_USER: ${BAKPGS3_USER}
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${BAKPGS3_USER}" ]
      interval: 2s
      retries: 120

  backup:
    image: pxjam/backup-postgres-s3:latest
    depends_on:
      postgres:
        condition: service_healthy
    container_name: backup-postgres-s3
    environment:
      BAKPGS3_ACCESS_KEY: ${BAKPGS3_ACCESS_KEY}
      BAKPGS3_BUCKET: ${BAKPGS3_BUCKET}
      BAKPGS3_CRON_TIME: ${BAKPGS3_CRON_TIME}
      BAKPGS3_DATABASE: ${BAKPGS3_DATABASE}
      BAKPGS3_HOST: ${BAKPGS3_HOST}
      BAKPGS3_ENDPOINT: ${BAKPGS3_ENDPOINT}
      BAKPGS3_PASSWORD: ${BAKPGS3_PASSWORD}
      BAKPGS3_PROJECT_NAME: ${BAKPGS3_PROJECT_NAME}
      BAKPGS3_REGION: ${BAKPGS3_REGION}
      BAKPGS3_TIMEZONE: ${BAKPGS3_REGION}
      BAKPGS3_SECRET_KEY: ${BAKPGS3_SECRET_KEY}
      BAKPGS3_USER: ${BAKPGS3_USER}

volumes:
  data:
